hmrc/trader-goods-profiles-data-store

app/uk/gov/hmrc/tradergoodsprofilesdatastore/config/DataStoreAppConfig.scala
app/uk/gov/hmrc/tradergoodsprofilesdatastore/controllers/ProfileController.scala
app/uk/gov/hmrc/tradergoodsprofilesdatastore/controllers/actions/IdentifierAction.scala
app/uk/gov/hmrc/tradergoodsprofilesdatastore/models/EnrolmentConfig.scala
app/uk/gov/hmrc/tradergoodsprofilesdatastore/models/requests/IdentifierRequest.scala
build.sbt
conf/application.conf
test/uk/gov/hmrc/tradergoodsprofilesdatastore/actions/AuthActionSpec.scala
test/uk/gov/hmrc/tradergoodsprofilesdatastore/actions/FakeIdentifierAction.scala
test/uk/gov/hmrc/tradergoodsprofilesdatastore/base/SpecBase.scala
test/uk/gov/hmrc/tradergoodsprofilesdatastore/base/TestConstants.scala
test/uk/gov/hmrc/tradergoodsprofilesdatastore/controllers/ProfileControllerSpec.scala

- Authorising users that are enrolled in CDS in the end points

TGP 1157: Added internal auth for the end-points

---

app/uk/gov/hmrc/tradergoodsprofilesdatastore/connectors/RouterConnector.scala
app/uk/gov/hmrc/tradergoodsprofilesdatastore/controllers/UpdateRecordController.scala
app/uk/gov/hmrc/tradergoodsprofilesdatastore/models/requests/UpdateRecordRequest.scala
app/uk/gov/hmrc/tradergoodsprofilesdatastore/repositories/RecordsRepository.scala
conf/app.routes
it/test/uk/gov/hmrc/tradergoodsprofilesdatastore/connectors/RouterConnectorSpec.scala
it/test/uk/gov/hmrc/tradergoodsprofilesdatastore/repositories/RecordsRepositorySpec.scala
test/uk/gov/hmrc/tradergoodsprofilesdatastore/controllers/UpdateRecordControllerSpec.scala

- Update end-point added
- Exceptions can be handled on the front-end when we make this call if required.

TGP-1630: added update end-point

---

README.md
build.sbt
pull_request_template.md

Update readme, alias commands and check list to follow that of TGP-2302

---

app/uk/gov/hmrc/tradergoodsprofilesdatastore/config/DataStoreAppConfig.scala
app/uk/gov/hmrc/tradergoodsprofilesdatastore/controllers/ProfileController.scala
app/uk/gov/hmrc/tradergoodsprofilesdatastore/repositories/ProfileRepository.scala
conf/app.routes
conf/application.conf
it/test/uk/gov/hmrc/tradergoodsprofilesdatastore/repositories/ProfileRepositorySpec.scala
test/uk/gov/hmrc/tradergoodsprofilesdatastore/controllers/ProfileControllerSpec.scala

TGP-2537: Attempt to revert all the important commits lines

---

app/uk/gov/hmrc/tradergoodsprofilesdatastore/connectors/RouterConnector.scala
app/uk/gov/hmrc/tradergoodsprofilesdatastore/controllers/UpdateRecordController.scala
app/uk/gov/hmrc/tradergoodsprofilesdatastore/models/requests/PatchRecordRequest.scala
app/uk/gov/hmrc/tradergoodsprofilesdatastore/models/requests/PutRecordRequest.scala
conf/app.routes
it/test/uk/gov/hmrc/tradergoodsprofilesdatastore/connectors/RouterConnectorSpec.scala
it/test/uk/gov/hmrc/tradergoodsprofilesdatastore/repositories/RecordsRepositorySpec.scala
test/uk/gov/hmrc/tradergoodsprofilesdatastore/controllers/UpdateRecordControllerSpec.scala

Tgp 2420/updating goods record patch and put via api

---

pull_request_template.md

TGP-2670: updated checklist template for PR

---

app/uk/gov/hmrc/tradergoodsprofilesdatastore/connectors/CustomsDataStoreConnector.scala
app/uk/gov/hmrc/tradergoodsprofilesdatastore/controllers/ProfileController.scala
it/test/uk/gov/hmrc/tradergoodsprofilesdatastore/connectors/CustomsDataStoreConnectorSpec.scala
test/uk/gov/hmrc/tradergoodsprofilesdatastore/controllers/ProfileControllerSpec.scala

TGP-2577: Improvement for handle 404 cds response

---

app/uk/gov/hmrc/tradergoodsprofilesdatastore/connectors/SecureDataExchangeProxyConnector.scala
it/test/uk/gov/hmrc/tradergoodsprofilesdatastore/connectors/SecureDataExchangeProxyConnectorSpec.scala

TGP-2790 removed sdes context path from url

---

app/uk/gov/hmrc/tradergoodsprofilesdatastore/controllers/DownloadDataSummaryController.scala
app/uk/gov/hmrc/tradergoodsprofilesdatastore/models/response/DownloadData.scala
it/test/uk/gov/hmrc/tradergoodsprofilesdatastore/connectors/SecureDataExchangeProxyConnectorSpec.scala

TGP-2791 updated sdes download schema

---

app/uk/gov/hmrc/tradergoodsprofilesdatastore/models/requests/ProfileRequest.scala
app/uk/gov/hmrc/tradergoodsprofilesdatastore/models/response/ProfileResponse.scala
app/uk/gov/hmrc/tradergoodsprofilesdatastore/repositories/ProfileRepository.scala
it/test/uk/gov/hmrc/tradergoodsprofilesdatastore/connectors/RouterConnectorSpec.scala
it/test/uk/gov/hmrc/tradergoodsprofilesdatastore/repositories/ProfileRepositorySpec.scala
test/uk/gov/hmrc/tradergoodsprofilesdatastore/controllers/ProfileControllerSpec.scala

Tgp 2697/create new ukims number change page

---

app/uk/gov/hmrc/tradergoodsprofilesdatastore/config/DataStoreAppConfig.scala
app/uk/gov/hmrc/tradergoodsprofilesdatastore/repositories/DownloadDataSummaryRepository.scala
conf/application.conf

TGP-2714: Add config value for dropping indexes and remove compound indexes

---

it/test/uk/gov/hmrc/tradergoodsprofilesdatastore/worker/ClearCacheWorkerIntegrationSpec.scala
test/uk/gov/hmrc/tradergoodsprofilesdatastore/actions/StoreLatestActionSpec.scala
test/uk/gov/hmrc/tradergoodsprofilesdatastore/controllers/CreateRecordControllerSpec.scala
test/uk/gov/hmrc/tradergoodsprofilesdatastore/controllers/DeleteRecordControllerSpec.scala
test/uk/gov/hmrc/tradergoodsprofilesdatastore/controllers/DownloadDataSummaryControllerSpec.scala
test/uk/gov/hmrc/tradergoodsprofilesdatastore/controllers/EmailControllerSpec.scala
test/uk/gov/hmrc/tradergoodsprofilesdatastore/controllers/FilterRecordsControllerSpec.scala
test/uk/gov/hmrc/tradergoodsprofilesdatastore/controllers/GetRecordsControllerSpec.scala
test/uk/gov/hmrc/tradergoodsprofilesdatastore/controllers/ProfileControllerSpec.scala
test/uk/gov/hmrc/tradergoodsprofilesdatastore/controllers/RecordsSummaryControllerSpec.scala
test/uk/gov/hmrc/tradergoodsprofilesdatastore/controllers/RequestAdviceControllerSpec.scala
test/uk/gov/hmrc/tradergoodsprofilesdatastore/controllers/UpdateRecordControllerSpec.scala
test/uk/gov/hmrc/tradergoodsprofilesdatastore/controllers/WithdrawAdviceControllerSpec.scala
test/uk/gov/hmrc/tradergoodsprofilesdatastore/services/ClearCacheServiceSpec.scala
test/uk/gov/hmrc/tradergoodsprofilesdatastore/services/SdesServiceSpec.scala
test/uk/gov/hmrc/tradergoodsprofilesdatastore/services/StoreRecordsServiceSpec.scala

TGP:2759: Refactor verifies in tests

---

it/test/uk/gov/hmrc/tradergoodsprofilesdatastore/repositories/ProfileRepositorySpec.scala
project/AppDependencies.scala
project/plugins.sbt

TGP-2852: update dependencies to latest versions

---

app/uk/gov/hmrc/tradergoodsprofilesdatastore/config/DataStoreAppConfig.scala
app/uk/gov/hmrc/tradergoodsprofilesdatastore/connectors/RouterConnector.scala
app/uk/gov/hmrc/tradergoodsprofilesdatastore/controllers/DownloadDataSummaryController.scala
app/uk/gov/hmrc/tradergoodsprofilesdatastore/controllers/ProfileController.scala
app/uk/gov/hmrc/tradergoodsprofilesdatastore/models/response/CorrelationId.scala
app/uk/gov/hmrc/tradergoodsprofilesdatastore/repositories/DownloadDataSummaryRepository.scala
conf/application.conf
it/test/uk/gov/hmrc/tradergoodsprofilesdatastore/connectors/RouterConnectorSpec.scala
it/test/uk/gov/hmrc/tradergoodsprofilesdatastore/repositories/DownloadDataSummaryRepositorySpec.scala
test/uk/gov/hmrc/tradergoodsprofilesdatastore/controllers/DownloadDataSummaryControllerSpec.scala
test/uk/gov/hmrc/tradergoodsprofilesdatastore/services/SdesServiceSpec.scala
test/uk/gov/hmrc/tradergoodsprofilesdatastore/services/StoreRecordsServiceSpec.scala

TGP-2821: added the ids and removed service and added tests

---

app/uk/gov/hmrc/tradergoodsprofilesdatastore/models/response/EoriHistoricItem.scala
it/test/uk/gov/hmrc/tradergoodsprofilesdatastore/connectors/CustomsDataStoreConnectorSpec.scala
project/plugins.sbt
test/uk/gov/hmrc/tradergoodsprofilesdatastore/controllers/ProfileControllerSpec.scala
test/uk/gov/hmrc/tradergoodsprofilesdatastore/models/response/EoriHistoryResponseSpec.scala

TGP-3032: Update eori history to use correct json

---

app/uk/gov/hmrc/tradergoodsprofilesdatastore/connectors/CustomsDataStoreConnector.scala
conf/application.conf
it/test/uk/gov/hmrc/tradergoodsprofilesdatastore/connectors/CustomsDataStoreConnectorSpec.scala

TGP-3050: Add a way to stub out verified email

---

project/AppDependencies.scala
project/plugins.sbt

TGP:3168: Update-auth-client-play-30-version

---

app/uk/gov/hmrc/tradergoodsprofilesdatastore/services/StoreRecordsService.scala
test/uk/gov/hmrc/tradergoodsprofilesdatastore/services/StoreRecordsServiceSpec.scala

TGP-3175: Fix live service issue by correctly handling a succesful recursive store

---

app/uk/gov/hmrc/tradergoodsprofilesdatastore/controllers/FilterRecordsController.scala
test/uk/gov/hmrc/tradergoodsprofilesdatastore/controllers/FilterRecordsControllerSpec.scala

TGP:3227: revert changes on pagination fix

---

conf/app.routes

TGP-3254: Accept reference as a query parameter

---

app/uk/gov/hmrc/tradergoodsprofilesdatastore/controllers/DownloadDataSummaryController.scala
app/uk/gov/hmrc/tradergoodsprofilesdatastore/models/TimeoutError.scala
project/AppDependencies.scala
project/plugins.sbt
test/uk/gov/hmrc/tradergoodsprofilesdatastore/controllers/DownloadDataSummaryControllerSpec.scala

TGP-3265: Handle conversation ID and initial request not found better

---

app/uk/gov/hmrc/tradergoodsprofilesdatastore/repositories/RecordsRepository.scala
it/test/uk/gov/hmrc/tradergoodsprofilesdatastore/repositories/RecordsRepositorySpec.scala
project/AppDependencies.scala

TGP-3285: Make isTraderReferenceIsUnique case insensitive to match that of the repository

---

app/uk/gov/hmrc/tradergoodsprofilesdatastore/controllers/FilterRecordsController.scala
app/uk/gov/hmrc/tradergoodsprofilesdatastore/repositories/RecordsRepository.scala

TGP-3322: Decode string before checking for duplicates

---

app/uk/gov/hmrc/tradergoodsprofilesdatastore/connectors/CustomsDataStoreConnector.scala
conf/application.conf
it/test/uk/gov/hmrc/tradergoodsprofilesdatastore/connectors/CustomsDataStoreConnectorSpec.scala
project/AppDependencies.scala
project/build.properties

TGP-3317: Email changes

---

app/uk/gov/hmrc/tradergoodsprofilesdatastore/connectors/CustomsDataStoreConnector.scala
app/uk/gov/hmrc/tradergoodsprofilesdatastore/controllers/ProfileController.scala
conf/application.conf
it/test/uk/gov/hmrc/tradergoodsprofilesdatastore/connectors/CustomsDataStoreConnectorSpec.scala
test/uk/gov/hmrc/tradergoodsprofilesdatastore/controllers/ProfileControllerSpec.scala

TGP-3318: Add feature to eori history to authorization

---

test/uk/gov/hmrc/tradergoodsprofilesdatastore/services/SdesServiceSpec.scala

TGP-3487: updated tests fropk ToDO to InProgress

---

app/uk/gov/hmrc/tradergoodsprofilesdatastore/models/response/Pagination.scala
project/AppDependencies.scala

TGP-3485 - address comment and directly utilise playframework to access config

---

app/uk/gov/hmrc/tradergoodsprofilesdatastore/repositories/RecordsRepository.scala

TGP-3483: update search terms not  allow regex

---

app/uk/gov/hmrc/tradergoodsprofilesdatastore/repositories/RecordsRepository.scala
build.sbt
conf/application.conf
project/AppDependencies.scala
project/plugins.sbt
test/uk/gov/hmrc/tradergoodsprofilesdatastore/services/SdesServiceSpec.scala

Revert to good state

---

app/uk/gov/hmrc/tradergoodsprofilesdatastore/repositories/RecordsRepository.scala
build.sbt
conf/application.conf
project/AppDependencies.scala
project/plugins.sbt
test/uk/gov/hmrc/tradergoodsprofilesdatastore/services/SdesServiceSpec.scala

This reverts commit 250714788afce4b2908d6569742160ebc47c6336, reversing changes made to 69df08a7952c5925eeb63c40f7eb572a685c7414.

Pull back all changes other than 7371470fcbbb

---

build.sbt
project/AppDependencies.scala
project/plugins.sbt

TGP-3523: update dependencies

---

app/uk/gov/hmrc/tradergoodsprofilesdatastore/controllers/DownloadDataSummaryController.scala
app/uk/gov/hmrc/tradergoodsprofilesdatastore/models/DownloadDataStatus.scala
app/uk/gov/hmrc/tradergoodsprofilesdatastore/repositories/DownloadDataSummaryRepository.scala
app/uk/gov/hmrc/tradergoodsprofilesdatastore/repositories/RecordsRepository.scala
conf/app.routes
it/test/uk/gov/hmrc/tradergoodsprofilesdatastore/repositories/DownloadDataSummaryRepositorySpec.scala
test/uk/gov/hmrc/tradergoodsprofilesdatastore/controllers/DownloadDataSummaryControllerSpec.scala

TGP-3550 - implement failed download banner

---

project/AppDependencies.scala

TGP-3571 Update Dependencies
